import type { HelpTopic } from "@/components/help/contextual-help";

type AdminHelpContent = { title: string; intro: string; topics: HelpTopic[] };

const DEFAULT_HELP: AdminHelpContent = {
  title: "Hjælp til administration",
  intro: "Sådan bruger du den aktuelle administrationsside.",
  topics: [{ title: "Arbejd sikkert", body: "Brug søgning og filtre til at finde posten, åbn den for at redigere, og kontrollér oplysningerne før du gemmer." }],
};

const HELP_BY_SECTION: Record<string, AdminHelpContent> = {
  "": { title: "Hjælp til Admin-overblik", intro: "Overblikket samler opgaver, der kræver handling.", topics: [{ title: "Opgaver", body: "Kortene åbner de filtrerede kontrakter, værker, visninger og gennemgange, der afventer behandling." }, { title: "Beskeder", body: "Ulæste medlemshenvendelser vises nederst og i menubadges." }] },
  kontrakter: { title: "Hjælp til kontrakter", intro: "Find, forbind og validér organisationens kontrakter.", topics: [{ title: "Statusser", body: "Kladde betyder, at kontrakten kræver gennemgang. Valideret betyder, at den kan bruges i systemets videre udbetalings- og statistikflow." }, { title: "Forbind med værk", body: "Søg først efter et eksisterende værk. Kontrakttype, overenskomst og datoer redigeres efter værkforbindelsen." }, { title: "AI-kilder og låste felter", body: "Det lille ¶-symbol, som kan ligne et lyn, viser kilden i kontrakten. Når du trykker på det, fremhæves den tekst i PDF'en, som AI'en brugte til feltet. Symbolet vises kun, når AI'en har gemt en konkret kildehenvisning, og det skjules på mobil. Den åbne hængelås betyder, at feltet kan opdateres ved Genindlæs kontrakt. Den lukkede hængelås beskytter en manuelt kontrolleret værdi mod at blive overskrevet af AI." }, { title: "Underskrift", body: "Systemet kontrollerer både tekstlige tegn på digital signering og lokale PDF-spor efter digitale eller håndskrevne underskrifter. Kontrollér altid resultatet i dokumentet før validering; Ukendt betyder, at systemet ikke kunne afgøre det sikkert." }, { title: "Serieafsnit", body: "Vælg de afsnit kontrakten gælder. En kontrakt kan gælde enkelte afsnit eller hele sæsonen." }, { title: "Filtre og massehandlinger", body: "Et aktivt rettighedshaverfilter deles med Værksarkiv. Markér flere kontrakter for samlet validering; permanent sletning bør kun bruges ved fejloprettelser." }] },
  vaerker: { title: "Hjælp til Værksarkiv", intro: "Vedligehold det fælles værkarkiv og de tilknyttede personer.", topics: [{ title: "Til godkendelse", body: "Nye værker og rettelser skal gennemgås, før oplysningerne bruges som endelige værksdata." }, { title: "Serier", body: "Fold en sæson ud for at se afsnit. Redigér sæsonen for fælles data og hvert afsnit for individuelle krediteringer." }, { title: "Afstem arbejdsandele", body: "Fanen Arbejdsandele viser en kø over værker, seriesæsoner og afsnit, hvor klippere, svar, indsigelser eller procentandele mangler administrativ afklaring. Åbn en række for at se portaloplysninger og vejledende DFI- og TMDb-krediteringer. Forbind, opret eller fravælg relevante personer, beregn derefter et kompromis, og kontrollér at andele og reserve tilsammen er 100 %. Oprettelse og forbindelse sender ingen invitation; invitation og påmindelse kræver et aktivt klik." }, { title: "Rettighedshavere", body: "Rolle og andel gemmes på relationen mellem værket og rettighedshaveren. En godkendt arbejdsandelsfordeling summerer sammen med en eventuel reserve til 100 %." }, { title: "Kontrakter", body: "Under tilknyttede kontrakter kan du åbne rettighedshaverens konkrete kontrakt eller forbinde en ny." }] },
  producenter: { title: "Hjælp til producenter", intro: "Producenten er en fælles identitet med en eller flere juridiske enheder.", topics: [{ title: "DFI og CVR", body: "Brug DFI til producentnavn og DFI-id. CVR, adresse og telefon hentes fra CVR-registeret eller indtastes manuelt." }, { title: "Flere CVR-numre", body: "Tilføj flere juridiske enheder, når samme producent bruger forskellige selskaber eller produktionsenheder." }, { title: "Producentforeningen", body: "Hent de offentlige medlemslister, kontrollér sikre og mulige matches og synkronisér de valgte. Producenter kan være medlem af flere grupper, og en tom kildeliste afmelder aldrig automatisk nogen." }, { title: "Værker og kontrakter", body: "Åbn en producent og fold de tilknyttede værker eller kontrakter ud. De indlæses først, når du åbner sektionen, og kan redigeres uden at forlade producentsiden." }] },
  rettighedshavere: { title: "Hjælp til rettighedshavere", intro: "Administrér medlemmer, portaladgang og relationer.", topics: [{ title: "Infokort og valg", body: "Infokortene viser alle ikke-arkiverede rettighedshavere, inviterede portalbrugere og personer med færdig onboarding. Tryk på et kort for at bruge det som filter. Listen viser, hvor mange der matcher, og hvor mange der er valgt." }, { title: "Filtre", body: "Alle viser alle ikke-arkiverede. Kun medlemmer viser aktive medlemmer i organisationen. Ikke-medlemmer viser personer uden aktivt medlemskab. Inviteret viser personer med portalbruger. Afventer onboarding viser inviterede, som ikke er færdige. Ikke inviteret viser personer uden portalbruger. Færdiggjort onboarding viser afsluttede onboardingforløb. Alle kontrakter valideret kræver mindst én kontrakt, og at alle kontrakter er valideret eller arkiveret. Arkiverede viser personer fjernet fra den aktive liste, men ikke permanent slettet." }, { title: "Søg og vælg", body: "Søgning dækker navn, e-mail, telefon og medlemsnummer og kombineres med det valgte filter. Valgte personer kan behandles samlet og forbliver valgt, hvis du skifter filter." }, { title: "Kræv onboarding igen", body: "I Rediger rettighedshaver kan du planlægge en ny fuld onboarding. Eksisterende oplysninger bevares, den aktuelle session fortsætter, og kravet aktiveres ved næste login. Et planlagt genkrav kan annulleres, mens førstegangs-onboarding aldrig kan springes over." }, { title: "Relationer", body: "Fold relationer ud for at åbne personens værker og kontrakter uden at miste den aktuelle side." }] },
  brugere: { title: "Hjælp til brugere", intro: "Administrér login, administratorroller og portaladgang separat.", topics: [{ title: "Roller", body: "Administratorroller styrer adminmenuen. Rettighedshaveradgang er en separat systemrolle og bevares ved ændring af administratorroller." }, { title: "Organisation", body: "En bruger kan kun redigeres i den organisation, som den aktuelle admin-kontekst er knyttet til." }] },
  kontraktgennemgang: { title: "Hjælp til kontraktgennemgang", intro: "Prioritér sager og dokumentér den juridiske vurdering.", topics: [{ title: "Køen", body: "Filtrér efter status og åbn den ældste sag først. Gem svar og markér sagen færdig, når medlemmet har fået en vurdering." }] },
  aftalelicens: { title: "Hjælp til visningsadministration", intro: "Kontrollér og godkend indberettede visninger.", topics: [{ title: "Kontrol", body: "Sammenhold værk, kanal, tidspunkt og dokumentation før godkendelse eller afvisning." }] },
  udbetalinger: { title: "Hjælp til udbetalinger", intro: "Forbered og kontrollér rettighedsbetalinger.", topics: [{ title: "Kontrol før betaling", body: "Kontrollér modtager, beregningsgrundlag og status før en udbetaling markeres klar." }] },
  organisation: { title: "Hjælp til organisation", intro: "Vedligehold organisationens profil og fælles opsætning.", topics: [{ title: "Ændringer", body: "Branding, afsenderoplysninger og integrationer påvirker alle brugere i organisationen." }] },
  statistik: { title: "Hjælp til statistik", intro: "Brug organisationens data til overblik og opfølgning.", topics: [{ title: "Filtre og grundlag", body: "Vælg periode og relevante filtre, og kontrollér datagrundlaget før tallene deles eller eksporteres." }] },
  indbetalinger: { title: "Hjælp til indbetalinger", intro: "Følg producenternes indbetalinger og det tilhørende datagrundlag.", topics: [{ title: "Afstemning", body: "Sammenhold producent, periode, beløb og tilknyttede værker. Brug status og filtre til at finde poster, der kræver opfølgning." }] },
  streaming: { title: "Hjælp til streaming", intro: "Administrér streamingproduktioner og deres rettighedsdata.", topics: [{ title: "Produktioner", body: "Åbn produktionen via titel eller navn, kontrollér deltagere og platform, og gem ændringer før en udbetaling registreres." }] },
  stamdata: { title: "Hjælp til stamdata", intro: "Vedligehold fælles satser, broadcastere og rettighedsopsætning.", topics: [{ title: "Fælles data", body: "Ændringer i stamdata kan påvirke flere beregninger og organisationer. Kontrollér derfor værdier og gyldighedsperioder før lagring." }] },
  gennemsigtighed: { title: "Hjælp til gennemsigtighed", intro: "Se og dokumentér grundlaget for rettighedsbetalingerne.", topics: [{ title: "Dokumentation", body: "Brug oversigterne til at forklare datakilder, beregninger og fordelinger for den valgte periode." }] },
  "ai-kontrolrum": { title: "Hjælp til AI-kontrolrum", intro: "Kontrollér AI-opsætning, modeller og automatiske behandlinger.", topics: [{ title: "Sikker ændring", body: "Test ændringer, før de bruges i drift. Nøgler og følsomme indstillinger må ikke deles eller indsættes i fritekstfelter." }] },
  "min-profil": { title: "Hjælp til Min profil", intro: "Vedligehold dine egne oplysninger og personlige valg.", topics: [{ title: "Profil", body: "Kontrollér kontaktoplysninger og personlige indstillinger, og gem kun oplysninger, der skal gælde for din bruger." }] },
  organisationer: { title: "Hjælp til organisationer", intro: "Administrér organisationer, abonnementer og adgange.", topics: [{ title: "Organisationstilknytning", body: "Kontrollér organisation og rolle, før en bruger flyttes eller får adgang til flere administrative funktioner." }] },
  beskeder: { title: "Hjælp til beskeder", intro: "Læs og besvar henvendelser fra medlemmer.", topics: [{ title: "Samtaler", body: "Åbn tråden, kontrollér hvilken sag beskeden vedrører, og svar i den eksisterende samtale, så historikken bevares." }] },
  barselspulje: { title: "Hjælp til barselspulje", intro: "Administrér oplysninger og sager knyttet til barselspuljen.", topics: [{ title: "Kontrol", body: "Kontrollér periode, person og dokumentation, før en sag ændrer status." }] },
  helligdagsfond: { title: "Hjælp til helligdagsfond", intro: "Administrér oplysninger og sager knyttet til helligdagsfonden.", topics: [{ title: "Kontrol", body: "Kontrollér periode, person og beregningsgrundlag, før en sag ændrer status." }] },
};

export function adminHelpForPath(pathname: string) {
  const section = pathname.replace(/^\/admin\/?/, "").split("/")[0] ?? "";
  return { section, content: HELP_BY_SECTION[section] ?? DEFAULT_HELP };
}
