import type {
    Contract,
    Work,
    Payment,
    Payout,
    MasterDataItem,
    SalaryDataPoint,
    RightsClauseStats,
    RegisteredWork,
    PensionStatsPoint,
    GenderDistribution,
    WorkingWeeksStats,
    PortalSettings,
    TransparencyReport,
    CreditEntry,
} from "./types"

// ── Portal Settings ─────────────────────────────────────────

export const mockPortalSettings: PortalSettings = {
    adminFeePercent: 5,
}

// ── Registered Works (for matching during upload) ───────────

export const mockRegisteredWorks: RegisteredWork[] = [
    {
        id: "rw1",
        title: "Drømmen om Danmark",
        category: "feature",
        premiereYear: 2025,
        registeredBy: ["Anna Sørensen"],
    },
    {
        id: "rw2",
        title: "Nordlys",
        category: "feature",
        premiereYear: 2025,
        registeredBy: ["Lars Mikkelsen"],
    },
    {
        id: "rw3",
        title: "Den Sidste Sæson",
        category: "tvSeries",
        premiereYear: 2026,
        registeredBy: [],
    },
    {
        id: "rw4",
        title: "Julefrokosten",
        category: "feature",
        premiereYear: 1976,
        registeredBy: ["Jørgen Hansen"],
    },
    {
        id: "rw5",
        title: "Julefrokosten",
        category: "feature",
        premiereYear: 2022,
        registeredBy: ["Sofie Wang"],
    },
]

// ── Works ───────────────────────────────────────────────────

export const mockWorks: Work[] = [
    {
        id: "w1",
        title: "Drømmen om Danmark",
        creditedRole: "Klipper",
        sharedCredit: true,
        sharedWith: ["Lars Mikkelsen"],
        duration: 118,
        contractId: "c1",
        category: "feature",
        premiereYear: 2025,
        rights: { svod: true, copydan: true, royalty: false },
    },
    {
        id: "w2",
        title: "Nordlys",
        creditedRole: "Klipper",
        sharedCredit: true,
        sharedWith: ["Anna Sørensen"],
        duration: 92,
        contractId: "c2",
        category: "feature",
        premiereYear: 2025,
        rights: { svod: true, copydan: true, royalty: true, royaltyPercent: 2.5 },
    },
    {
        id: "w3",
        title: "Den Sidste Sæson",
        creditedRole: "Klipper",
        sharedCredit: false,
        duration: 0,
        episodes: [
            { number: 1, title: "Den formørkede skov", duration: 33 },
            { number: 2, title: "Vendepunktet", duration: 38 },
            { number: 3, title: "Lys i mørket", duration: 35 },
        ],
        contractId: "c3",
        category: "tvSeries",
        premiereYear: 2026,
        rights: { svod: true, copydan: true, royalty: false },
    },
    {
        id: "w4",
        title: "Bag Kulisserne",
        creditedRole: "Klipper",
        sharedCredit: false,
        duration: 58,
        contractId: "c4",
        category: "documentary",
        premiereYear: 2025,
        rights: { svod: false, copydan: true, royalty: false },
    },
    {
        id: "w5",
        title: "Stormfulde Nætter",
        creditedRole: "Klipper",
        sharedCredit: true,
        sharedWith: ["Marie Jensen"],
        duration: 105,
        contractId: "c5",
        category: "feature",
        premiereYear: 2026,
        rights: { svod: true, copydan: true, royalty: true, royaltyPercent: 3.0 },
    },
]

// ── Contracts ───────────────────────────────────────────────

export const mockContracts: Contract[] = [
    {
        id: "c1",
        userId: "u1",
        userName: "Anna Sørensen",
        title: "Drømmen om Danmark",
        category: "feature",
        creditedRole: "Klipper",
        duration: 118,
        premiereDate: "2025-09-15",
        premiereYear: 2025,
        fileUrl: "/contracts/c1.pdf",
        status: "approved",
        uploadedAt: "2025-06-10",
        extractedData: {
            salary: 52000,
            salaryUnit: "monthly",
            startDate: "2025-03-01",
            endDate: "2025-08-31",
            producerName: "Zentropa Entertainments",
            pensionPercent: 8,
            pensionSupplement: 4160,
            personalSupplement: 2500,
            workingWeeks: 26,
            svod: true,
            copydan: true,
            royalty: false,
            aiDataMiningClause: true,
            distribution: ["DR", "Netflix"],
            collectiveAgreement: true,
            collectiveAgreementName: "Dansk Film Overenskomst",
            gender: "female",
        },
    },
    {
        id: "c2",
        userId: "u2",
        userName: "Lars Mikkelsen",
        title: "Nordlys",
        category: "feature",
        creditedRole: "Klipper",
        duration: 92,
        premiereDate: "2025-11-20",
        premiereYear: 2025,
        fileUrl: "/contracts/c2.pdf",
        status: "review",
        uploadedAt: "2025-08-05",
        extractedData: {
            salary: 48000,
            salaryUnit: "monthly",
            startDate: "2025-05-01",
            endDate: "2025-10-15",
            producerName: "Nordisk Film Production",
            pensionPercent: 8,
            pensionSupplement: 3840,
            personalSupplement: 1800,
            workingWeeks: 24,
            svod: true,
            copydan: true,
            royalty: true,
            royaltyPercent: 2.5,
            aiDataMiningClause: true,
            distribution: ["TV2", "Biograf"],
            collectiveAgreement: true,
            collectiveAgreementName: "Dansk Film Overenskomst",
            gender: "male",
        },
    },
    {
        id: "c3",
        userId: "u1",
        userName: "Anna Sørensen",
        title: "Den Sidste Sæson",
        category: "tvSeries",
        creditedRole: "Klipper",
        duration: 0,
        episodes: [
            { number: 1, title: "Den formørkede skov", duration: 33 },
            { number: 2, title: "Vendepunktet", duration: 38 },
            { number: 3, title: "Lys i mørket", duration: 35 },
        ],
        premiereDate: "2026-02-01",
        premiereYear: 2026,
        fileUrl: "/contracts/c3.pdf",
        status: "pending",
        uploadedAt: "2025-12-01",
    },
    {
        id: "c4",
        userId: "u3",
        userName: "Marie Jensen",
        title: "Bag Kulisserne",
        category: "documentary",
        creditedRole: "Klipper",
        duration: 58,
        premiereDate: "2025-07-10",
        premiereYear: 2025,
        fileUrl: "/contracts/c4.pdf",
        status: "approved",
        uploadedAt: "2025-04-20",
        extractedData: {
            salary: 38000,
            salaryUnit: "monthly",
            startDate: "2025-02-01",
            endDate: "2025-06-30",
            producerName: "DR Produktion",
            pensionPercent: 6,
            personalSupplement: 0,
            workingWeeks: 22,
            svod: false,
            copydan: true,
            royalty: false,
            aiDataMiningClause: false,
            distribution: ["DR"],
            collectiveAgreement: false,
            gender: "female",
        },
    },
    {
        id: "c5",
        userId: "u4",
        userName: "Kasper Holm",
        title: "Stormfulde Nætter",
        category: "feature",
        creditedRole: "Klipper",
        duration: 105,
        premiereDate: "2026-04-15",
        premiereYear: 2026,
        fileUrl: "/contracts/c5.pdf",
        status: "review",
        uploadedAt: "2026-01-10",
        extractedData: {
            salary: 55000,
            salaryUnit: "monthly",
            startDate: "2025-11-01",
            endDate: "2026-03-31",
            producerName: "SF Studios",
            pensionPercent: 10,
            pensionSupplement: 5500,
            personalSupplement: 3000,
            otherSupplements: "Transporttillæg: 2.000 kr/md",
            workingWeeks: 22,
            svod: true,
            copydan: true,
            royalty: true,
            royaltyPercent: 3.0,
            aiDataMiningClause: true,
            distribution: ["Netflix", "Biograf", "DR"],
            collectiveAgreement: true,
            collectiveAgreementName: "Dansk Film Overenskomst",
            gender: "male",
            specialNotes: "Ekstra klippeuge i post-produktion aftalt mundtligt.",
        },
    },
    {
        id: "c6",
        userId: "u5",
        userName: "Pernille Agger",
        title: "Under Overfladen",
        category: "documentary",
        creditedRole: "Instruktør",
        duration: 72,
        premiereDate: "2025-05-01",
        premiereYear: 2025,
        fileUrl: "/contracts/c6.pdf",
        status: "approved",
        uploadedAt: "2024-11-08",
        extractedData: {
            salary: 45000,
            salaryUnit: "monthly",
            startDate: "2024-09-01",
            endDate: "2025-04-30",
            producerName: "Koncern TV",
            pensionPercent: 8,
            pensionSupplement: 3600,
            personalSupplement: 1200,
            workingWeeks: 34,
            svod: true,
            copydan: true,
            royalty: false,
            aiDataMiningClause: false,
            distribution: ["TV2", "Viaplay"],
            collectiveAgreement: true,
            collectiveAgreementName: "TV-Overenskomsten",
            gender: "female",
        },
    },
    {
        id: "c7",
        userId: "u6",
        userName: "Emil Rasmussen",
        title: "Midnatssolen",
        category: "feature",
        creditedRole: "Fotograf",
        duration: 95,
        premiereDate: "2024-12-20",
        premiereYear: 2024,
        fileUrl: "/contracts/c7.pdf",
        status: "approved",
        uploadedAt: "2024-06-15",
        extractedData: {
            salary: 58000,
            salaryUnit: "monthly",
            startDate: "2024-03-01",
            endDate: "2024-11-30",
            producerName: "Zentropa Entertainments",
            pensionPercent: 10,
            pensionSupplement: 5800,
            personalSupplement: 4000,
            workingWeeks: 39,
            svod: true,
            copydan: true,
            royalty: true,
            royaltyPercent: 2.0,
            aiDataMiningClause: true,
            distribution: ["Biograf", "DR", "HBO"],
            collectiveAgreement: true,
            collectiveAgreementName: "Dansk Film Overenskomst",
            gender: "male",
        },
    },
]

// ── Payments ────────────────────────────────────────────────

export const mockPayments: Payment[] = [
    {
        id: "p1",
        workId: "w1",
        workTitle: "Drømmen om Danmark",
        source: "svod",
        amount: 12500,
        adminFeePercent: 5,
        adminFee: 625,
        netAmount: 11875,
        paidAt: "2025-12-15",
    },
    {
        id: "p2",
        workId: "w1",
        workTitle: "Drømmen om Danmark",
        source: "copydan",
        amount: 8200,
        adminFeePercent: 5,
        adminFee: 410,
        netAmount: 7790,
        paidAt: "2025-11-01",
    },
    {
        id: "p3",
        workId: "w4",
        workTitle: "Bag Kulisserne",
        source: "copydan",
        amount: 4500,
        adminFeePercent: 5,
        adminFee: 225,
        netAmount: 4275,
        paidAt: "2025-10-15",
    },
    {
        id: "p4",
        workId: "w2",
        workTitle: "Nordlys",
        source: "royalties",
        amount: 3200,
        adminFeePercent: 5,
        adminFee: 160,
        netAmount: 3040,
        paidAt: "2026-01-10",
    },
]

// ── Payouts ─────────────────────────────────────────────────

export const mockPayouts: Payout[] = [
    {
        id: "po1",
        workId: "w1",
        workTitle: "Drømmen om Danmark",
        poolAmount: 25000,
        adminFee: 1250,
        distributions: [
            { userId: "u1", userName: "Anna Sørensen", sharePercent: 60, amount: 14250 },
            { userId: "u2", userName: "Lars Mikkelsen", sharePercent: 40, amount: 9500 },
        ],
        createdAt: "2025-12-01",
        exported: true,
    },
]

// ── Master Data ─────────────────────────────────────────────

export const mockRoles: MasterDataItem[] = [
    { id: "r1", name: "Klipper", active: true },
    { id: "r2", name: "Instruktør", active: true },
    { id: "r3", name: "Fotograf", active: true },
    { id: "r4", name: "Lyddesigner", active: true },
    { id: "r5", name: "Producer", active: true },
    { id: "r6", name: "Manuskriptforfatter", active: true },
    { id: "r7", name: "Scenograf", active: false },
]

export const mockCategories: MasterDataItem[] = [
    { id: "cat1", name: "Spillefilm", active: true },
    { id: "cat2", name: "Kortfilm", active: true },
    { id: "cat3", name: "TV-Serie", active: true },
    { id: "cat4", name: "Dokumentarfilm", active: true },
    { id: "cat5", name: "Dokumentarserie", active: true },
    { id: "cat6", name: "TV-underholdningsprogram", active: true },
    { id: "cat7", name: "Reality", active: true },
    { id: "cat8", name: "Sport", active: true },
]

// ── Statistics ──────────────────────────────────────────────

export const mockSalaryData: SalaryDataPoint[] = [
    { year: 2020, dailyRate: 2800, monthlyRate: 42000 },
    { year: 2021, dailyRate: 2950, monthlyRate: 43500 },
    { year: 2022, dailyRate: 3100, monthlyRate: 45000 },
    { year: 2023, dailyRate: 3250, monthlyRate: 47000 },
    { year: 2024, dailyRate: 3400, monthlyRate: 49500 },
    { year: 2025, dailyRate: 3550, monthlyRate: 52000 },
]

export const mockRightsClauseStats: RightsClauseStats[] = [
    { category: "Spillefilm", svodPercent: 78, copydanPercent: 92, royaltyPercent: 35 },
    { category: "TV-Serie", svodPercent: 85, copydanPercent: 88, royaltyPercent: 22 },
    { category: "Dokumentar", svodPercent: 45, copydanPercent: 95, royaltyPercent: 12 },
    { category: "Kortfilm", svodPercent: 30, copydanPercent: 70, royaltyPercent: 8 },
]

export const mockPensionStats: PensionStatsPoint[] = [
    { year: 2020, avgPensionPercent: 6.2, avgPersonalSupplement: 800 },
    { year: 2021, avgPensionPercent: 6.8, avgPersonalSupplement: 1100 },
    { year: 2022, avgPensionPercent: 7.4, avgPersonalSupplement: 1400 },
    { year: 2023, avgPensionPercent: 7.8, avgPersonalSupplement: 1800 },
    { year: 2024, avgPensionPercent: 8.2, avgPersonalSupplement: 2200 },
    { year: 2025, avgPensionPercent: 8.5, avgPersonalSupplement: 2600 },
]

export const mockGenderDistribution: GenderDistribution[] = [
    { gender: "Kvinde", count: 42, avgSalary: 46500 },
    { gender: "Mand", count: 58, avgSalary: 49200 },
    { gender: "Andet", count: 3, avgSalary: 44800 },
]

export const mockWorkingWeeksStats: WorkingWeeksStats[] = [
    { year: 2020, avgWeeks: 28, medianWeeks: 26 },
    { year: 2021, avgWeeks: 30, medianWeeks: 28 },
    { year: 2022, avgWeeks: 29, medianWeeks: 27 },
    { year: 2023, avgWeeks: 31, medianWeeks: 30 },
    { year: 2024, avgWeeks: 32, medianWeeks: 30 },
    { year: 2025, avgWeeks: 30, medianWeeks: 28 },
]

// ── Transparency Reports ────────────────────────────────────

export const mockTransparencyReports: TransparencyReport[] = [
    {
        id: "tr1",
        year: 2025,
        title: "Gennemsigtighedsrapport 2025",
        totalCollected: 3850000,
        totalDistributed: 3542000,
        adminCosts: 308000,
        sources: [
            { name: "Create Denmark", collected: 1850000, distributed: 1720000 },
            { name: "CopyDan", collected: 1400000, distributed: 1302000 },
            { name: "SVOD", collected: 600000, distributed: 520000 },
        ],
        memberCount: 148,
        publishedAt: "2026-03-15",
    },
    {
        id: "tr2",
        year: 2024,
        title: "Gennemsigtighedsrapport 2024",
        totalCollected: 3420000,
        totalDistributed: 3150000,
        adminCosts: 270000,
        sources: [
            { name: "Create Denmark", collected: 1650000, distributed: 1530000 },
            { name: "CopyDan", collected: 1270000, distributed: 1180000 },
            { name: "SVOD", collected: 500000, distributed: 440000 },
        ],
        memberCount: 142,
        publishedAt: "2025-03-10",
    },
    {
        id: "tr3",
        year: 2023,
        title: "Gennemsigtighedsrapport 2023",
        totalCollected: 2980000,
        totalDistributed: 2750000,
        adminCosts: 230000,
        sources: [
            { name: "Create Denmark", collected: 1420000, distributed: 1310000 },
            { name: "CopyDan", collected: 1160000, distributed: 1080000 },
            { name: "SVOD", collected: 400000, distributed: 360000 },
        ],
        memberCount: 136,
        publishedAt: "2024-03-12",
    },
]

// ── Credit Entries ─────────────────────────────────────────

export const mockCredits: CreditEntry[] = [
    {
        id: "cr1",
        workTitle: "Drømmen om Danmark",
        category: "feature",
        premiereYear: 2025,
        creditedRole: "Klipper",
        memberName: "Anna Sørensen",
        memberId: "u1",
        producerName: "Zentropa Entertainments",
        verified: true,
        imdbUrl: "https://www.imdb.com/title/tt0000001",
    },
    {
        id: "cr2",
        workTitle: "Drømmen om Danmark",
        category: "feature",
        premiereYear: 2025,
        creditedRole: "Klipper",
        memberName: "Lars Mikkelsen",
        memberId: "u2",
        producerName: "Zentropa Entertainments",
        verified: true,
    },
    {
        id: "cr3",
        workTitle: "Nordlys",
        category: "feature",
        premiereYear: 2025,
        creditedRole: "Klipper",
        memberName: "Lars Mikkelsen",
        memberId: "u2",
        producerName: "Nordisk Film Production",
        verified: true,
        imdbUrl: "https://www.imdb.com/title/tt0000002",
    },
    {
        id: "cr4",
        workTitle: "Bag Kulisserne",
        category: "documentary",
        premiereYear: 2025,
        creditedRole: "Klipper",
        memberName: "Marie Jensen",
        memberId: "u3",
        producerName: "DR Produktion",
        verified: false,
        notes: "Venter på IMDb-opdatering",
    },
    {
        id: "cr5",
        workTitle: "Stormfulde Nætter",
        category: "feature",
        premiereYear: 2026,
        creditedRole: "Klipper",
        memberName: "Kasper Holm",
        memberId: "u4",
        producerName: "SF Studios",
        verified: false,
    },
    {
        id: "cr6",
        workTitle: "Under Overfladen",
        category: "documentary",
        premiereYear: 2025,
        creditedRole: "Instruktør",
        memberName: "Pernille Agger",
        memberId: "u5",
        producerName: "Koncern TV",
        verified: true,
    },
    {
        id: "cr7",
        workTitle: "Midnatssolen",
        category: "feature",
        premiereYear: 2024,
        creditedRole: "Fotograf",
        memberName: "Emil Rasmussen",
        memberId: "u6",
        producerName: "Zentropa Entertainments",
        verified: true,
        imdbUrl: "https://www.imdb.com/title/tt0000003",
    },
    {
        id: "cr8",
        workTitle: "Den Sidste Sæson",
        category: "tvSeries",
        premiereYear: 2026,
        creditedRole: "Klipper",
        memberName: "Anna Sørensen",
        memberId: "u1",
        producerName: "DR Produktion",
        verified: false,
    },
]
