-- Denne migration er erstattet af 20260825010000_rettighedsmidler_delta.sql
-- som håndterer at nogle tabeller allerede eksisterede i produktionsdatabasen.
-- Filen bevares tom så migrationsnummeret ikke genbruges.
